version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_SITE_URL: ${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}
        NEXT_PUBLIC_RFQ_ENDPOINT: ${NEXT_PUBLIC_RFQ_ENDPOINT:-}
        NEXT_PUBLIC_RFQ_EMAIL: ${NEXT_PUBLIC_RFQ_EMAIL:-sales@example.com}
        ASSET_BASE_URL: ${ASSET_BASE_URL:-}
        NEXT_PUBLIC_ASSET_BASE_URL: ${NEXT_PUBLIC_ASSET_BASE_URL:-}
        BAIDU_TONGJI_ID: ${BAIDU_TONGJI_ID:-}
        NEXT_PUBLIC_BAIDU_TONGJI_ID: ${NEXT_PUBLIC_BAIDU_TONGJI_ID:-}
        TENCENT_CAPTCHA_APP_ID: ${TENCENT_CAPTCHA_APP_ID:-}
        NEXT_PUBLIC_TENCENT_CAPTCHA_APP_ID: ${NEXT_PUBLIC_TENCENT_CAPTCHA_APP_ID:-}
    container_name: garment-site-web
    restart: unless-stopped
    ports:
      - "80:80"
